

Currency = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Currency"
Fragment = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Fragment"
Oils = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Oils"
Incubators = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Incubators"
Scarabs = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Scarabs"
Fossils = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Fossils"
Resonators = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Resonators"
Essence = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Essence"
DivinationCards = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Divination Cards"
Prophecies = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Prophecies"
SkillGems = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Skill Gems"
BaseTypes = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Base Types"
HelmetEnchants = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Helmet Enchants"
UniqueMaps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Maps"
Maps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Maps"
UniqueJewels = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Jewels"
UniqueFlasks = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Flasks"
UniqueWeapons = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Weapons"
UniqueArmours = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Armours"
UniqueAccessories = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Accessories"
Beasts = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Beasts"
Wombgifts = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Wombgifts"
Runegrafts = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Runegrafts"
AllflameEmbers = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Allflame Embers"
Tattoos = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Tattoos"
Omens = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Omens"
DjinnCoins = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Djinn Coins"
Artifacts = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Artifacts"
ForbiddenJewels = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Forbidden Jewels"
ShrineBelts = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Shrine Belts"
UniqueTinctures = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Tinctures"
UniqueRelics = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Relics"
SkillGems = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Skill Gems"
ClusterJewels = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Cluster Jewels"
Maps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Maps"
BlightedMaps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Blighted Maps"
BlightRavagedMaps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Blight-ravaged Maps"
UniqueMaps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Unique Maps"
ValdoMaps = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Valdo Maps"
DeliriumOrbs = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Delirium Orbs"
Invitations = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Invitations"
Scarabs = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Scarabs"
Astrolobes = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Astrolobes"
Memories = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Memories"
Temples = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Temples"
BaseTypes = "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Base Types"
Fossils	= "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Fossils"
Resonators	= "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Resonators"
Beasts	= "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Beasts"
Essences	= "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Essences"
Vials	= "https://poe.ninja/poe1/api/economy/exchange/current/overview?league=Mirage&type=Vials"
